global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flowers-rose'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus_data_generator_rose:9000']
  - job_name: 'flowers-sunflower'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus_data_generator_sunflower:9000']
  - job_name: 'flower-tulip'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus_data_generator_tulip:9000']